language: python
python:
- 2.6
- 2.7
addons:
  sauce_connect: true
install: pip install -r requirements.txt
before_script:
- sh -e /etc/init.d/xvfb start
- python run.py &
env:
  global:
  - DISPLAY=':99.0'
  - secure: qVLhAgHooFDUPydF66vHRLE2KOPqI7/hYzkkx8lXY0wO+EnKGWsG2UkRpj7yItve7kU2TC4bQWGC03sgtpDHSAwnEpeim7RgCvmCF3F2mYdExS1itbfrZ1ExayeorFZK83mWCLTMKyfGBSceDVbbWHuD1aXJFABBpGXp83Prq3M=
  - secure: R5jNEwwTc5wheqtI2L0mFnlmH3p/o1ZJOrFiGU8fflfQCYpiY+rZsLLUe2UeYbJlLdkP8xnB3k/h1B3b0byeCvLGORue83FFbCmjmQSBpuDw+vXUQ7ysPbPl5tWxQzqIA3u+z5UB27L6bsVJxmPpPKa/lcylgteUHnqStNNoDJo=
  matrix:
  - SAUCE_PLATFORM='Windows 8' SAUCE_BROWSER='FIREFOX' SAUCE_BROWSER_VERSION=''
  - SAUCE_PLATFORM='Windows 8' SAUCE_BROWSER='CHROME' SAUCE_BROWSER_VERSION=''
  - SAUCE_PLATFORM='Windows 8' SAUCE_BROWSER='INTERNETEXPLORER' SAUCE_BROWSER_VERSION='10'
  - SAUCE_PLATFORM='Linux' SAUCE_BROWSER='FIREFOX' SAUCE_BROWSER_VERSION=''
  - SAUCE_PLATFORM='Linux' SAUCE_BROWSER='CHROME' SAUCE_BROWSER_VERSION=''
  - SAUCE_PLATFORM='Linux' SAUCE_BROWSER='ANDROID' SAUCE_BROWSER_VERSION='4.3'
  - SAUCE_PLATFORM='OS X 10.9' SAUCE_BROWSER='IPHONE' SAUCE_BROWSER_VERSION='7'
script: py.test -vv
